In [1]:
import pandas as pd

In [2]:
import requests

In [9]:
import requests
import pandas as pd

response = requests.get(
    "https://api.openweathermap.org/data/2.5/weather?q=Delhi&units=metric&appid=YOUR_API_KEY"
)

data = response.json()

df = pd.json_normalize(data)

print(df.head())

   cod                                            message
0  401  Invalid API key. Please see https://openweathe...

In [17]:
import requests
import pandas as pd

response = requests.get(
    "https://www.omdbapi.com/?i=tt3896198&apikey=edde5443"
)

data = response.json()

# df = pd.json_normalize(data)

df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [18]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
df.shape

(0, 0)

In [24]:
import requests
import pandas as pd

url = "https://movie-database-api1.p.rapidapi.com/list_movies.json?limit=20"

headers = {
    "x-rapidapi-key": "YOUR_API_KEY",
    "x-rapidapi-host": "movie-database-api1.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

print(data)

# Optional
df = pd.json_normalize(data)
print(df.head())

{'messages': 'The API is unreachable, please contact the API provider', 'info': 'Your Client (working) ---> Gateway (working) ---> API (not working)'}